### ISSUE TITLE
Having issue getting this App working

### ISSUE THREAD

**Issue by NEK4TE** [nextcloud/user_retention#241]
Hello,

I am having issue getting this up working, i have more then 50k registered users, i am sure that a lot of them did not log in for more then 60 days (amount of days set in configuration of this app).

However, checking number of users via users section of Nextcloud, i am not seeing reduced numbers.

Did check documentation, as well done recommended command via occ , yet, still doesn't work.

[cldhost@server public_html]$ php occ config:app:set user_retention keep_users_without_login --value=no
Config value keep_users_without_login for app user_retention set to no

Using latest version of App, 1.3.0

Any suggestion / direction to make this work properly is greatly appreciated.

**Comment by nickvergessen** [comment]
So on the first run of the apps daily background job users are discovered, and they are then also not deleted until the discovery is "old enough":
https://github.com/nextcloud/user_retention/blob/master/lib/BackgroundJob/ExpireUsers.php#L151

**Comment by NEK4TE** [comment]
Hello,

We have this plugin installed for a long time, cron jobs have been running for months, yet, we are not seeing any users deleted.

Is there a way to make sure everything runs in background properly in regards to cron (that is needed for this App?)

Please advise
