### ISSUE TITLE
Send emails/notifications to users before the expiration date is reached.

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/user_retention#30]
Like #29 but before the actual expiration to warn them.

Needs a new input to pick the number of days after which user should receive a warning email.

**Comment by heri410** [comment]
That would be very usfull.

**Comment by nickvergessen** [comment]
@tcitworld you self-assigned 1.5y ago. Still plan to implement this?

**Comment by tcitworld** [comment]
I still need it in the foreseeable future, but feel free to assign yourself.

**Comment by tcitworld** [comment]
I didn't mean to close the issue, sorry about that.

**Comment by tcitworld** [comment]
@nickvergessen This can be closed now, right?

**Comment by nickvergessen** [comment]
Yes, thanks.

**Comment by nickvergessen** [comment]
Added the UI task to https://github.com/nextcloud/user_retention/issues/118
