### ISSUE TITLE
Allow to disable users first before deleting them

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/user_retention#31]
Since deleting users is a rather destructive action, it would be nice to first disable them before actually deleting them *just in case*.

Needs a new input field to set the number of days after which an user should be disabled.

**Comment by coffeemesh** [comment]
I really would appreciate this feature! Is anyone actively working on this?
Otherwise I will be looking into it and hopefully figure out how to implement it myself, any and every help would be appreciated.

**Comment by nickvergessen** [comment]
I guess the code place is around
https://github.com/nextcloud/user_retention/blob/master/lib/BackgroundJob/ExpireUsers.php#L117

You can take inspiration from the files retention:
https://github.com/nextcloud/files_retention/blob/master/lib/BackgroundJob/RetentionJob.php#L173-L175

**Comment by tcitworld** [comment]
I had started to write an app for this a while ago, feel free to have a look https://framagit.org/framasoft/nextcloud/purge
