### ISSUE TITLE
Show "last login" on users page

### ISSUE THREAD

**Issue by h-2** [nextcloud/user_retention#310]
I really like this app, but immediate removal is kind of brutal, so I support the other issues that address this.

However, for now, it would already be really helpful if I, as the admin, could see when a specific account was last used. Could this information be added to the "users" overview? Then I can manually remove accounts or ping individual users. Maybe this would be a feature request for core?

**Comment by nickvergessen** [comment]
The user management has a setting for this in the bottom left menu?

**Comment by acsfer** [comment]
Yes, this is by default.
Just activate the checkbox in the bottom left "Settings" in the "Users" menu (don't need to use this app).

![image](https://user-images.githubusercontent.com/12234510/121666635-c2b72b80-caa9-11eb-9f5d-f1ef4ef12a53.png)
