### ISSUE TITLE
Account disabling feature (in addition to the deletion feature)

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/user_retention#480]
Hello, 
Good extension idea but it scares me. I talked my boss about it and he had the same fear reaction.
I think it would be nice (and less dangerous) to **only disable account by default** (this would be the default behavior), and then, only if you check an supplementary option in the settings, the account would be deleted (instead of disabling, for administrators who really want it). The deletion option would by disabled by default **and marked as a dangerous option**.
Deleting an account and its data is a violent thing, that's why disabling it would seem to me to be more secure than deleting it directly.
What do you think ?

**Comment by nickvergessen** [comment]
Duplicate of #31 ?

**Comment by nickvergessen** [comment]
Or well it's an extension to that, but can only implement it in one way with both requests

**Comment by Jerome-Herbinet** [comment]
OK thanks for the answer, I close my issue.
