### ISSUE TITLE
Not able to configure disabling accounts

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/user_retention#538]
t.nc.c in 25.0.6
tp.nc.c in 26.0

The configuration options are different from what is displayed in the readme.

![image](https://user-images.githubusercontent.com/87175513/233941604-4338881e-8dea-4062-b839-a18836180e7c.png)

It is not possible to configure disabling account after a certain time of inactivity.

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/user_retention/issues/533
