### ISSUE TITLE
What date is used for the last login?

### ISSUE THREAD

**Issue by Mvntee** [nextcloud/user_retention#600]
Hello
I recently installed the application on my nextcloud (it is in 27.0.1 and will be upgraded to 27.0.2 next week).
All accounts were created 2 years ago ( ~800 accounts ). The users all logged in to their accounts after they were created.
I've set the accounts to be deactivated after 6 months of inactivity, but no account has been deactivated. (application installed 2 weeks ago )

So we have to wait another 6 months for the accounts to be deactivated automatically?

Isn't the date of the last nextcloud login used? ( php occ user:lastseen $username )

Thanks

**Comment by nickvergessen** [comment]
There is a "sanity" check that basically uses the install date of the app as another condition. So if you set it to 6months, you should see deactivations/deletions only 6 months after first time the app was enabled.

**Comment by mejo-** [comment]
Exactly what @nickvergessen said. I'll close this issue because your question was answered :relaxed:
