### ISSUE TITLE
No account deactivations so far...

### ISSUE THREAD

**Issue by hansimausisteffiwurstbrot** [nextcloud/user_retention#678]
Hey,
we got 1.11.0 installed on Nextcloud 28.0.2
These are the settings.

![Screenshot from 2024-02-26 12-59-43](https://github.com/nextcloud/user_retention/assets/71875177/0c861009-c123-49cb-a89f-431e1c4797ad)

Although we got accounts that haven't been logged in for more than three years, the app hasn't  deactivated a single one.

Is there anything we're missing to get the app working?

Thx!

**Comment by mejo-** [comment]
Dear @hansimausisteffiwurstbrot,

accounts that haven't been activate *before* the app was enabled will not be deactivated. The app will start counting on the day it got enabled. So your first accounts should get deactivated 730 days after the app was enabled.
