### ISSUE TITLE
expiration?

### ISSUE THREAD

**Issue by hansimausisteffiwurstbrot** [nextcloud/user_retention#731]
Hey, 
what is "account expiration" about?
Is the account deactivated?
Are users informed about the "expiration", too?

Thanks!

**Comment by nickvergessen** [comment]
> what is "account expiration" about?

Cleaning up users that no longer use Nextcloud

> Is the account deactivated?

No, they are deleted

> Are users informed about the "expiration", too?

They can be reminded up front:
https://github.com/nextcloud/user_retention#-reminders

At the moment there is no "inform after/during deletion", but it's planned with https://github.com/nextcloud/user_retention/issues/29
